services:
  magrathea:
    build: { context: ., dockerfile: apps/magrathea/Dockerfile }
    ports: ["8081:80"]
    cpus: 1.0
    mem_limit: 512m

  slim:
    build: { context: ., dockerfile: apps/slim/Dockerfile }
    ports: ["8082:80"]
    cpus: 1.0
    mem_limit: 512m

  laravel:
    build: { context: ., dockerfile: apps/laravel/Dockerfile }
    ports: ["8083:80"]
    cpus: 1.0
    mem_limit: 512m

  symfony:
    build: { context: ., dockerfile: apps/symfony/Dockerfile }
    ports: ["8084:80"]
    cpus: 1.0
    mem_limit: 512m
