[general]
	use_environment = "production"

[production]
	db_host = "localhost"
	db_name = "bench_unused"
	db_user = "bench"
	db_pass = "bench"
	db_port = "3306"
	site_path = "/var/www/app"
	logs_path = "../logs"
	cache_path = "../cache"
	timezone = "UTC"
	server_url = "http://localhost:8081"
